# Generated by Django 2.0.5 on 2018-05-07 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_dashatable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DashaTable',
        ),
    ]
