# Generated by Django 2.0.5 on 2018-05-07 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashatable',
            old_name='body',
            new_name='image',
        ),
    ]
